project_id = "ystpkgdmhraxpyaumoug"

[functions.admin-manual-otp]
verify_jwt = false

[functions.auth-register]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.auth-verify-otp]
verify_jwt = false

[functions.auth-resend-otp]
verify_jwt = false

[functions.google-sheets-proxy]
verify_jwt = false

[functions.import-from-sheets]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.admin-get-users]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.get-child-records]
verify_jwt = false
